/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * API Specification
 * OpenAPI spec version: 1.0.0
 */
export type ListPetsParams = {
/**
 * How many items to return at one time (max 100)
 */
limit?: number;
};

export interface Error {
  code: number;
  message: string;
}

export interface Pet {
  id: number;
  name: string;
  tag?: string;
}

/**
 * @maxItems 100
 */
export type Pets = Pet[];

