/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * API Specification
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  ListPetsParams,
  Pet,
  Pets
} from './aPISpecification.schemas'



  export const getAPISpecification = () => {
/**
 * @summary List all pets
 */
const listPets = <TData = AxiosResponse<Pets>>(
    params?: ListPetsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/pets`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Create a pet
 */
const createPets = <TData = AxiosResponse<void>>(
    pet: Pet, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/pets`,
      pet,options
    );
  }

/**
 * @summary Info for a specific pet
 */
const showPetById = <TData = AxiosResponse<Pet>>(
    petId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/pets/${petId}`,options
    );
  }

return {listPets,createPets,showPetById}};
export type ListPetsResult = AxiosResponse<Pets>
export type CreatePetsResult = AxiosResponse<void>
export type ShowPetByIdResult = AxiosResponse<Pet>
